import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Scanner;

public class ContactSystem {
    public static void main(String[] args) {
        boolean runcontact = false;
        Scanner scanner = new Scanner(System.in);
        while(!runcontact){
            System.out.println("1. Add Contacts.");
            System.out.println("2. View Contacts.");
            System.out.println("3. Update Contacts.");
            System.out.println("4. Remove Contacts.");
            System.out.println("5. Exit The Program.");
            System.out.print("Enter your choice:");
            int choice = scanner.nextInt();
            switch(choice){
                case 1:
                    addContact();
                    break;
                case 2:
                    viewContact();
                    break;
                case 3:
                    updateContact();
                    break;
                case 4:
                    removeContact();
                    break;
                case 5:
                    runcontact = true;
                    System.out.println("You have exited the program.");
                    break;
                default:
                    System.out.println("Enter a valid choice!");
                    break;
            }



        }












    }
    private static void viewContact() {



    }

    private static void updateContact() {

    }

    private static void removeContact() {
    }




    //adds the contacts into a textfile.
    private static  void addContact(){
        ArrayList<Contacts> contactList = new ArrayList<>();
        Scanner scanner = new Scanner(System.in);

        System.out.print("Enter the contact's name: ");
        String name = scanner.nextLine();

        System.out.print("Enter the contact's phone no: ");
        long phoneNumber = scanner.nextLong();

        scanner.nextLine(); // to take up the extra line generated by the nextLong().
        System.out.print("Enter the contact's email:");
        String email = scanner.nextLine();

        Contacts contacts = new Contacts(name,phoneNumber,email);
        contactList.add(contacts);
        try {
            FileWriter fileWriter = new FileWriter("Contacts.txt");
            fileWriter.write(String.valueOf(contactList));
            System.out.println("Contact Successfully added.");
            fileWriter.close();
        } catch (IOException e) {
            throw new RuntimeException(e);
        }

    }


}
